const phrases = [
  "The community's dedication to renewable energy.",
  "Santa Barbara's strong environmental policies.",
  "The increasing number of electric vehicles on the road.",
  "Local organizations committed to climate action.",
  "The restoration of native ecosystems and habitats.",
  "Educational programs raising awareness about climate change.",
  "The shift towards sustainable agriculture practices.",
  "Collaborative efforts to protect our coastline.",
  "The resilience of Santa Barbara's natural landscapes.",
  "The youth leading climate strikes and movements.",
  "New solar projects powering local homes and businesses.",
  "Conservation efforts to reduce water waste.",
  "Innovative clean energy startups in the area.",
  "The commitment of local farmers to organic farming.",
  "Community gardens and urban farming initiatives.",
  "The preservation of open spaces and wildlife corridors.",
  "The push for zero-waste goals across the county.",
  "Advancements in green building technologies.",
  "The city's investment in public transportation.",
  "Ongoing efforts to reduce single-use plastics.",
  "Volunteers planting trees to restore urban forests.",
  "Policies that prioritize environmental justice.",
  "The growing number of climate-conscious local businesses.",
  "Support for electric bike and scooter infrastructure.",
  "Santa Barbara's vibrant environmental activism scene.",
  "Collaborative efforts to preserve the marine environment.",
  "Commitments to reduce carbon emissions year over year.",
  "The strong sense of community around sustainable living.",
  "Coastal restoration projects to protect against rising seas.",
  "Public awareness of the importance of reducing carbon footprints.",
  "Collaborations between scientists and policymakers for climate solutions.",
  "Investment in desalination technologies to conserve water.",
  "Locals embracing sustainable lifestyles and practices.",
  "The protection of Santa Barbara’s marine sanctuaries.",
  "Advocacy for stronger wildfire prevention measures.",
  "Programs that encourage drought-resistant landscaping.",
  "The transition to more sustainable tourism practices.",
  "Commitment to preserving the natural beauty of the region.",
  "Efforts to make the city more bike-friendly.",
  "The support for small, eco-friendly businesses in the community.",
];
